spring:
  profiles:
    active: local
    group:
      local: local, datasource, security
      prod: prod, datasource, security
  config:
    import: optional:file:.env[.properties]

  jackson:
    serialization:
      fail-on-empty-beans: false

swagger:
  server: ${EC2_HOST:}