spring:
  profiles:
    active: local
    group:
      local: local, datasource
      prod: prod, datasource
  config:
    import: optional:file:.env[.properties]

  jackson:
    serialization:
      fail-on-empty-beans: false

swagger:
  server: ${EC2_HOST:}

tour:
  api: ${TOUR_API}